# Generated by Django 3.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ticket',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
